# Makefile for the USM player ( WATCOM C Version )
# It can be use by borland make.exe and watcom wmake.exe
#
# (c) 1996 FreddyV/Useless

TARGET = void.exe

# USM play lib file
LIB   = usmppmw.lib
#LIB   = ..\LIB\usmpd4g.lib

# USM play include files directory
INC   = .

# WATCOM C include directory
CINC  = ..\..\WATCOM\H

# PMODE/W or DOS/4GW Extender (Change also the ASMPARAM section)
SYSTEM = pmodew
#SYSTEM = dos4g

#-----------------------------------------------------------------------------

# C compiler parameters
# ---------------------
#

CPARAM   = -i=$(CINC) -i=$(INC)

ASM      = TASM $(ASMPARAM)
C        = WCC386
LINK     = WLINK

OBJLIST     = void.obj

#
#                       ** Files link **
#

$(TARGET)   : $(OBJLIST)
                $(LINK) @WATCOM.LNK file void file $(LIB) system $(SYSTEM) name $(TARGET)
#     pmwlite /c4 $(TARGET)

void.obj    : void.c $(INC)\usmplay.h
                $(C) $(CPARAM) void.c