
TARGET   = 15bpptst

O        = obj
C        = cpp

CC       = wpp386.exe
LD       = wlink.exe
CFLAGS   = -fp5 -zp16 -oneatx -s -et
LFLAGS   =

# LIBS     = ..\..\etc\libpng\libpng.lib
# LIBSTR   = library {$(LIBS)}

OBJS     = $(TARGET).$(O)
OBJSTR   = file {$(OBJS)}

all: $(TARGET).exe

$(TARGET).exe: $(OBJS) .symbolic
	$(LD) name $(TARGET) $(OBJSTR) $(LIBSTR) system pmode $(LFLAGS)

$(TARGET).$(O) : $(TARGET).$(C)
	$(CC) $< $(CFLAGS)
	
	
# clean all
clean: .symbolic
	del *.$(O)
	del *.exe
	del *.err